Django_bolg/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('', home),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 登出
    path('logout/', views.user_logout, name='logout'),
    # 注册
    path('register/', views.user_register, name='register'),
    # 删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 编辑个人信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    {% block head %}{% endblock head %}
</head>

<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}
{% block footer %}{% endblock footer %}
<script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>

{% block script %}{% endblock script %}
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br>
</div>
<footer class="py-3 bg-dark footer fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white ">Copyright &copy; https://github.com/aduner 2020</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="/">Home</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'article:article_list' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'article:article_create' %}">New Blog</a>
                </li>
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                             <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>Personal information</a>
                            <a class="dropdown-item" href="{% url "userprofile:logout" %}">logout</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">delete user</a>
                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'userprofile:login' %}">Login</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

templates/home.html
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 定义放置文章标题的div容器 -->
    <div class="container">
        <h1>欢迎来到我的博客 </h1>
    </div>
{% endblock content %}