Django_bolg/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('', home),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 登出
    path('logout/', views.user_logout, name='logout'),
    # 注册
    path('register/', views.user_register, name='register'),
    # 删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 编辑个人信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from django.urls import reverse

# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 浏览量
    total_views = models.PositiveIntegerField(default=0)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)
        db_table = 'Article'

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
from django import forms
from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
import markdown
from django.contrib.auth.models import User
from .forms import ArticlePostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'total_views':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 增加 search 到 context
    context = {'articles': articles, 'order': order, 'search': search}

    return render(request, 'article/list.html', context)


# def article_list(request):
#     # 取出所有博客文章
#     articles = ArticlePost.objects.all()
#     # 需要传递给模板（templates）的对象
#     context = {'articles': articles}
#     # render函数：载入模板，并返回context对象
#     return render(request, 'article/list.html', context)


def article_detail(request, id):
    # 取出文章评论
    comments = Comment.objects.filter(article=id)
    article = ArticlePost.objects.get(id=id)
    article.total_views += 1
    article.save(update_fields=['total_views'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    # 将markdown语法渲染成html样式
    article.body = md.convert(article.body)

    # 新增了md.toc对象
    context = {'article': article, 'toc': md.toc, 'comments': comments}
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 写文章的视图
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
            # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    author_id = ArticlePost.objects.get(id=id).author_id
    user_id = request.user.id
    if author_id != user_id:
        return HttpResponse("你没有权限修改此用户信息。")
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """
    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    author_id = article.author_id
    user_id = request.user.id
    if author_id != user_id:
        return HttpResponse("你没有权限修改此用户信息。")
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form}
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <!-- 写文章表单 -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!-- 提交文章的表单 -->
                <form method="post" action=".">
                    <!-- Django中需要POST数据的地方都必须有csrf_token -->
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">文章标题</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <style>
        h1, h2, h3, h4, h5, h6 {
            font-weight: bold
        }
    </style>
    <!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <!-- 标题及作者 -->
            <div class="col-9" style="min-height: 578px">
                <div class="row">
                    <h1 class="title col-10">{{ article.title }}</h1>
                    {#                    <a class="col-2 title" id="delete"#}
                    {#                       href="javascript:if(confirm('确实要删除该内容吗?'))location='{% url "article:article_delete" article.id %}'">#}
                    {#                        Delect#}
                    {#                    </a>#}
                    {% if user == article.author %}
                        <a class="modify" id="update" href="{% url "article:article_update" article.id %}">
                            Updata</a>
                        <span class="modify">|</span>
                        <a class="modify" id="delete" href="#" onclick="confirm_safe_delete()">
                            Delect
                        </a>
                    {% endif %}

                    <form id="safe_delete"
                          action="{% url 'article:article_safe_delete' article.id %}"
                          method="POST"
                          style="display:none;">
                        {% csrf_token %}
                        <button type="submit">submit</button>
                    </form>

                </div>
                <!-- 文章正文 -->
                <h6 class="author">作者：{{ article.author }}</h6>
                <div class="col-12">
                    <p>{{ article.body|safe }}</p>
                </div>
            </div>

            <div class="col-3 mt-4 ">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>


        <div>
            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                            action="{% url 'comment:post_comment' article.id %}"
                            method="POST"
                    >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <textarea
                                    type="text"
                                    class="form-control"
                                    id="body"
                                    name="body"
                                    rows="2"
                            style="width: 60%"></textarea>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}
        </div>

        <div >
            <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
                                        {% if user == article.author %}
                        <a class="modify" id="update" href="{% url "article:article_update" article.id %}">
                            Updata</a>
                        <span class="modify">|</span>
                        <a class="modify" id="delete" href="#" onclick="confirm_safe_delete()">
                            Delect
                        </a>
                    {% endif %}
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body }}</pre>
                {% endfor %}
            </div>
        </div>
    </div>




    <script>
        function confirm_safe_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除这篇文章吗？",
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                }
            })
        }
    </script>
{% endblock content %}
{% block footer %}
    <script>document.getElementsByTagName('footer')[0].classList.remove("fixed-bottom");</script>
{% endblock footer %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/article_list.css' %}">
{% endblock head %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <br>
    <!-- 定义放置文章标题的div容器 -->
    <div class="container">

        <div class="row">
            <nav aria-label="breadcrumb" class="col-2 ">
                <ol class="breadcrumb sort">
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:article_list' %}">
                            最新
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:article_list' %}?order=total_views">
                            最热
                        </a>
                    </li>
                </ol>
            </nav>

            <!-- 新增，搜索栏 -->
            <div class="row search_article">
                <div class="col-auto">
                    <form class="form-inline">
                        <label class="sr-only">content</label>
                        <input type="text"
                               class="form-control mb-2 mr-sm-2 search_article"
                               name="search"
                               placeholder="Search the article..."
                               required
                        >
                    </form>
                </div>
            </div>
        </div>

        <!-- 新增，搜索提示语 -->
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        <div class="row mt-2">
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-9 mb-4 ">
                    <!-- 卡片容器 -->
                    <a href="{% url 'article:article_detail' article.id %}">
                        <div class="blog_card">
                            <!-- 标题 -->
                            <h4 class="card-header border-bottom-0">{{ article.title }}
                                <span style="float: right;">
                                    <small class="col align-self-end" style="color: gray;font-size: small!important;">
                                        浏览: {{ article.total_views }}
                                    </small>
                            </span>
                            </h4>

                            <!-- 摘要 -->
                            <div class="card-body">
                                <p class="card-text">{{ article.body|slice:'100' }}...</p>

                            </div>

                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
        <div class="pagination row ">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}" class="btn ">
                    &laquo; 首页
                </a>
                {#                <span>...</span>#}
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                   class="btn "
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                   class="btn"
                >
                    {{ articles.next_page_number }}
                </a>
                {#                <span>...</span>#}
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                   class="btn"
                >
                    尾页 &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>

{% endblock content %}
{% block footer %}
    {% if articles.len >= 4 %}
        <script>document.getElementsByTagName('footer')[0].classList.remove("fixed-bottom");</script>
    {% endif %}
{% endblock footer %}

templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                        <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                        <textarea type="text" class="form-control" id="body" name="body"
                                  rows="12">{{ article.body }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}